version: '3.3'

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: bkr_db
    volumes:
      - ./data:/var/lib/postgresql/data
  
  api:
    build: .
    volumes:
      - ./:/app
    restart: always
    command: uwsgi --thunder-lock --ini uwsgi.ini
#    command: python myapi.py
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db